export const dicionaryZenit = (letter) => {
    switch(letter) {
        case 'z':
            return 'p';
        case 'p':
            return 'z';
        case 'e':
            return 'o';
        case 'o':
            return 'e';
        case 'n':
            return 'l';
        case 'l':
            return 'n';
        case 'i':
            return 'a';
        case 'a':
            return 'i';
        case 't':
            return 'r';
        case 'r':
            return 't';
        case 'Z':
            return 'P';
        case 'P':
            return 'Z';
        case 'E':
            return 'O';
        case 'O':
            return 'E';
        case 'N':
            return 'L';
        case 'L':
            return 'N';
        case 'I':
            return 'A';
        case 'A':
            return 'I';
        case 'T':
            return 'R';
        case 'R':
            return 'T';
        default:
            return letter; 
    }
}

export const dicionaryRot = (letter) => {
    switch(letter) {
        case 'a':
            return 'n';
        case 'n':
            return 'a';
        case 'b':
            return 'o';
        case 'o':
            return 'b';
        case 'c':
            return 'p';
        case 'p':
            return 'c';
        case 'd':
            return 'q';
        case 'q':
            return 'd';
        case 'e':
            return 'r';
        case 'r':
            return 'e';
        case 'f':
            return 's';
        case 's':
            return 'f';
        case 'g':
            return 't';
        case 't':
            return 'g';
        case 'h':
            return 'u';
        case 'u':
            return 'h';
        case 'i':
            return 'v';
        case 'v':
            return 'i';
        case 'j':
            return 'w';
        case 'w':
            return 'j';
        case 'k':
            return 'x';
        case 'x':
            return 'k';
        case 'l':
            return 'y';
        case 'y':
            return 'l';
        case 'm':
            return 'z';
        case 'z':
            return 'm';
        case 'A':
            return 'N';
        case 'N':
            return 'A';
        case 'B':
            return 'O';
        case 'O':
            return 'B';
        case 'C':
            return 'P';
        case 'P':
            return 'C';
        case 'D':
            return 'Q';
        case 'Q':
            return 'D';
        case 'E':
            return 'R';
        case 'R':
            return 'E';
        case 'F':
            return 'S';
        case 'S':
            return 'F';
        case 'G':
            return 'T';
        case 'T':
            return 'G';
        case 'H':
            return 'U';
        case 'U':
            return 'H';
        case 'I':
            return 'V';
        case 'V':
            return 'I';
        case 'J':
            return 'W';
        case 'W':
            return 'J';
        case 'K':
            return 'X';
        case 'X':
            return 'K';
        case 'L':
            return 'Y';
        case 'Y':
            return 'L';
        case 'M':
            return 'Z';
        case 'Z':
            return 'M';
        default:
            return letter; 
    }
}